<a href="https://colab.research.google.com/github/madejej/data-science-bootcamp/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Basics

In [4]:
import numpy as np
np.__version__

'1.19.5'

In [7]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'a

In [ ]:
help(np.array)

#####1D Array

In [10]:
x = np.array([1, 3])
x

array([1, 3])

In [12]:
print(x)

[1 3]


In [14]:
type(x)

numpy.ndarray

In [16]:
x.ndim  #dimension check

1

In [18]:
x.shape

(2,)

In [20]:
x.size #number of elements in x

2

In [21]:
x.dtype #shows type of data in the array

dtype('int64')

#####2D Arrays

In [23]:
x = np.array([[1,3], [-3, 4]])
x

array([[ 1,  3],
       [-3,  4]])

In [29]:
x.ndim

2

In [31]:
x.shape

(2, 2)

In [33]:
x.dtype

dtype('int64')

#####3D Arrays

In [35]:
x = np.array([[[1, 2, 3], [4, 3, 2]],
              
              [[6, 3, 1], [9, 6, 5]]])
x

array([[[1, 2, 3],
        [4, 3, 2]],

       [[6, 3, 1],
        [9, 6, 5]]])

In [37]:
x.ndim

3

In [38]:
x.shape

(2, 2, 3)